# espanso configuration file
secure_input_notification: false
enable_passive: true
passive_key: SHIFT
passive_match_regex: "(?P<name>;\\p{L}+)(/(?P<args>.*)/)?"

matches:
  # Arrow
  - trigger: "\\rarrow"
    replace: "→"
  - trigger: "\\larrow"
    replace: "←"
  - trigger: "\\uarrow"
    replace: "↑"
  - trigger: "\\darrow"
    replace: "↓"
  - trigger: "\\lrarrow"
    replace: "⟷"

  # Mac Navigation & Modifier
  - trigger: "\\tab"
    replace: "⇥"
  - trigger: "\\shift"
    replace: "⇧" 
  - trigger: "\\del"
    replace: "⌫"
  - trigger: "\\fdel"
    replace: "⌦"
  - trigger: "\\esc"
    replace: "⎋"
  - trigger: "\\ctrl"
    replace: "⌃"
  - trigger: "\\home"
    replace: "↖"
  - trigger: "\\end"
    replace: "↘"
  - trigger: "\\return"
    replace: "↩"
  - trigger: "\\enter"
    replace: "⌅"
  - trigger: "\\space"
    replace: "␣"
  - trigger: "\\pgup"
    replace: "⇞"
  - trigger: "\\pgdown"
    replace: "⇟"
  - trigger: "\\caps"
    replace: "⇪"
  - trigger: "\\eject"
    replace: "⏏"
  - trigger: "\\cmd"
    replace: "⌘"
  - trigger: "\\opt"
    replace: "⌥"
  - trigger: "\\shift"
    replace: "⇧"

  # Extra Remarks
  - trigger: "\\--"
    replace: "—"
  - trigger: "\\bul"
    replace: "•"
  - trigger: "\\shrug"
    replace: "¯\\_(ツ)_/¯"